"""PDF export helpers for SalesAI intelligence briefs."""

from __future__ import annotations

from datetime import datetime
from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.platypus import (
    HRFlowable,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
)


MARGIN = 50


def _clean(text: object) -> str:
    return str(text or "").replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def _section(story: list, title: str, styles: dict) -> None:
    story.append(Spacer(1, 8))
    story.append(HRFlowable(width="100%", thickness=0.6, color=colors.HexColor("#d9dee7")))
    story.append(Spacer(1, 8))
    story.append(Paragraph(title, styles["section"]))
    story.append(Spacer(1, 4))


def _bullet(story: list, text: str, styles: dict) -> None:
    story.append(Paragraph(f"&bull; {_clean(text)}", styles["body"]))
    story.append(Spacer(1, 3))


def _footer(canvas, doc, confidence_note: str, source_urls: list[str]) -> None:
    canvas.saveState()
    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(colors.HexColor("#6b7280"))
    footer_lines = [
        "Generated by SalesAI for Consulting Point · Confidential",
        _clean(confidence_note)[:150],
    ]
    if source_urls:
        footer_lines.append("Sources: " + " | ".join(source_urls[:3])[:160])

    y = 34
    for line in footer_lines:
        canvas.drawString(MARGIN, y, line)
        y -= 9
    canvas.restoreState()


def generate_pdf_brief(state: dict) -> bytes:
    """Generate a clean PDF intelligence brief from a pipeline state."""
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=MARGIN,
        leftMargin=MARGIN,
        topMargin=MARGIN,
        bottomMargin=MARGIN,
        title="SalesAI Intelligence Brief",
    )

    base_styles = getSampleStyleSheet()
    styles = {
        "title": ParagraphStyle(
            "SalesAITitle",
            parent=base_styles["Title"],
            fontName="Helvetica-Bold",
            fontSize=18,
            leading=22,
            textColor=colors.HexColor("#111827"),
            spaceAfter=6,
        ),
        "subtitle": ParagraphStyle(
            "SalesAISubtitle",
            parent=base_styles["Normal"],
            fontName="Helvetica",
            fontSize=10,
            leading=13,
            textColor=colors.HexColor("#4b5563"),
            spaceAfter=8,
        ),
        "section": ParagraphStyle(
            "SalesAISection",
            parent=base_styles["Heading2"],
            fontName="Helvetica-Bold",
            fontSize=13,
            leading=16,
            textColor=colors.HexColor("#111827"),
            spaceAfter=4,
        ),
        "body": ParagraphStyle(
            "SalesAIBody",
            parent=base_styles["BodyText"],
            fontName="Helvetica",
            fontSize=10,
            leading=13,
            textColor=colors.HexColor("#1f2937"),
        ),
    }

    profile = state.get("profile") or {}
    name = profile.get("name", "Unknown")
    role = profile.get("current_role", "Unknown")
    firm = profile.get("current_firm", "Unknown")
    generated_at = datetime.now().strftime("%d %b %Y")
    source_urls = [source.get("url", "") for source in state.get("sources", []) if source.get("url")]
    confidence_note = state.get("confidence_note", "")

    story = [
        Paragraph(f"Intelligence Brief: {_clean(name)}", styles["title"]),
        Paragraph(f"{_clean(role)} at {_clean(firm)} · Generated {generated_at}", styles["subtitle"]),
    ]

    _section(story, "Profile Summary", styles)
    story.append(Paragraph(_clean(profile.get("career_summary", "No profile summary available.")), styles["body"]))

    _section(story, "Commercial Priorities", styles)
    for item in state.get("commercial_priorities", []):
        _bullet(story, f"{item.get('priority', '')} ({item.get('confidence', 'unknown')} confidence)", styles)

    _section(story, "Pain Points", styles)
    for item in state.get("pain_points", []):
        _bullet(story, f"{item.get('pain_point', '')} ({item.get('confidence', 'unknown')} confidence)", styles)

    _section(story, "Conversation Angles", styles)
    for idx, angle in enumerate(state.get("conversation_angles", []), start=1):
        story.append(Paragraph(f"{idx}. {_clean(angle.get('angle', ''))}", styles["body"]))
        story.append(Spacer(1, 3))

    _section(story, "Recommended Outreach", styles)
    drafts = state.get("outreach_drafts", {}) or {}
    draft_labels = {
        "warm_referral": "Warm Referral",
        "cold_value_first": "Cold Value First",
        "event_trigger": "Event Trigger",
    }
    for key, label in draft_labels.items():
        story.append(Paragraph(f"<b>{label}</b>: {_clean(drafts.get(key, ''))}", styles["body"]))
        story.append(Spacer(1, 4))

    _section(story, "Recent Signals", styles)
    signals = state.get("recent_signals", [])
    if signals:
        for signal in signals:
            _bullet(story, signal.get("signal", ""), styles)
    else:
        story.append(Paragraph("No recent trigger events detected.", styles["body"]))

    if confidence_note or source_urls:
        _section(story, "Confidence & Sources", styles)
        if confidence_note:
            story.append(Paragraph(_clean(confidence_note), styles["body"]))
            story.append(Spacer(1, 4))
        for url in source_urls[:8]:
            _bullet(story, url, styles)

    doc.build(
        story,
        onFirstPage=lambda canvas, doc: _footer(canvas, doc, confidence_note, source_urls),
        onLaterPages=lambda canvas, doc: _footer(canvas, doc, confidence_note, source_urls),
    )
    pdf = buffer.getvalue()
    buffer.close()
    return pdf
